CREATE TABLE Puzzle (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL
);

CREATE TABLE AnswerGroup (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    puzzle_id INT NOT NULL REFERENCES Puzzle(id),
    level INT NOT NULL,
    group_name TEXT NOT NULL
);

CREATE TABLE GroupMember (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_id INT NOT NULL REFERENCES AnswerGroup(id),
    word TEXT NOT NULL,
    position INT NOT NULL
);